# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.8.0
minimal_mistakes_skin: mint


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Dr. Kakia Chatsiou"
title separator: " - "
email: "mailto:achats@essex.ac.uk"
url: "https://kakiac.github.io"
# this means to ignore newlines until "baseurl:"
description: ">- Senior Research Officer at the ESRC Business and Local Government Data Research Centre"

breadcrumbs: true
words_per_minute : 200

twitter_username: "@kakiac"
github_username: "kakiac"

search: true


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dr. Kakia Chatsiou"
  avatar : "https://www1.essex.ac.uk/people-images/CHATS23303.jpg"
  bio    : "Senior Research Officer <br> at the <a style='color: black;' style='text-decoration: underline;' href='http://www.blgdataresearch.org/'>ESRC Business and Local Government Data Research Centre</a>"
  location : "Suffolk, UK"
  links:
    - label: "Website"
      icon: "fab fa-fw fa-link"
      url: "https://www.essex.ac.uk/people/chats23303/kakia-chatsiou"
    - label: "Twitter"
     # icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@kakiac"
    - label: "GitHub"
     # icon: "fab fa-fw fa-github"
      url: "https://github.com/kakiac"
    - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kakia.c"
 
## links:  
 ##   - label: "Google Maps"
 ##     icon: "fas fa-fw fa-thumbtack fa-lg"
 ##     url: https://www.google.com/maps/search/Block+C,+Unit+2+Parkside+Nesfield+Road+University+of+Essex+Wivenhoe+Park+Colchester+Essex+CO4+3SQ/@51.8798427,0.9416097,17z
 ##   - label: "Email"
 ##     icon: "fas fa-fw fa-envelope fa-lg"
 ##    url: mailto:philipp.broniecki@essex.ac.uk



# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@kakiac"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kakiac"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kakia.c"
    - label: "Academia"
      icon: "fab fa-fw fa-academia"
      url: "https://essex.academia.edu/KakiaChatsiou"
    - label: "Arxiv"
      icon: "fab fa-fw fa-arxiv"
      url: " https://arxiv.org/search/cs?searchtype=author&query=Chatsiou%2C+K"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: ""
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: ""
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: ""
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai-lg"
      url: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=HxLVwXEAAAAJ&gmla=AJsN-F7eg_E5VM-R-W5CSPn4VPMchxMlPCjm5luTY3sxiKNQSF6phNMVEBx_pqpZyo0mHLDkX5PssRbWuHCjnPDXGBhZGj4r7oEHLBpcpY5-XoOUVyv7L8LE-plf7BlS6FGzSHxHQ2RG"
    - label: "ORCID"
      icon: "ai ai-orcid ai-lg"
      url: "https://orcid.org/0000-0001-9214-4404"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
